### ISSUE TITLE
IllegalArgumentException: ratingType should not be null.

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/autopilot#14]
Enabling ratings  for code challenges ,is throwing errors in Autopilot.

Exception
com.topcoder.management.phase.PhaseHandlingException: Fail to retrieve the user info when sending email.
        at com.cronos.onlinereview.phases.AbstractPhaseHandler.sendEmail(AbstractPhaseHandler.java:672)
        at com.cronos.onlinereview.phases.AbstractPhaseHandler.sendPhaseEmails(AbstractPhaseHandler.java:521)
        at com.cronos.onlinereview.phases.AbstractPhaseHandler.sendPhaseEmails(AbstractPhaseHandler.java:415)
        at com.cronos.onlinereview.phases.AppealsResponsePhaseHandler.perform(AppealsResponsePhaseHandler.java:272)
        at com.cronos.onlinereview.phases.PRAppealResponsePhaseHandler.perform(PRAppealResponsePhaseHandler.java:65)
        at com.topcoder.management.phase.DefaultPhaseManager.end(DefaultPhaseManager.java:735)
        at com.topcoder.management.phase.autopilot.impl.DefaultProjectPilot.doPhaseOperation(DefaultProjectPilot.java:495)
        at com.topcoder.management.phase.autopilot.impl.DefaultProjectPilot.processPhase(DefaultProjectPilot.java:456)
        at com.topcoder.management.phase.autopilot.impl.DefaultProjectPilot.advancePhases(DefaultProjectPilot.java:402)
        at com.topcoder.management.phase.autopilot.AutoPilot.advanceProject(AutoPilot.java:366)
        at com.topcoder.management.phase.autopilot.AutoPilot.advanceProjects(AutoPilot.java:332)
        at com.topcoder.management.phase.autopilot.AutoPilot.advanceProjects(AutoPilot.java:283)
        at com.topcoder.management.phase.autopilot.AutoPilotJob.execute(AutoPilotJob.java:343)
        at com.topcoder.management.phase.autopilot.AutoPilotJob.run(AutoPilotJob.java:311)
        at java.lang.Thread.run(Thread.java:722)
Caused by: com.cronos.onlinereview.external.RetrievalException: Some parameters of RatingType.getRatingType() or RatingInfo.ctor() invalid.
        at com.cronos.onlinereview.external.impl.DBUserRetrieval.updateRatings(DBUserRetrieval.java:524)
        at com.cronos.onlinereview.external.impl.DBUserRetrieval.selectRating(DBUserRetrieval.java:655)
        at com.cronos.onlinereview.external.impl.DBUserRetrieval.retrieveUsers(DBUserRetrieval.java:383)
        at com.cronos.onlinereview.external.impl.DBUserRetrieval.retrieveUsers(DBUserRetrieval.java:237)
        at com.cronos.onlinereview.external.impl.DBUserRetrieval.retrieveUser(DBUserRetrieval.java:175)
        at com.cronos.onlinereview.phases.AbstractPhaseHandler.sendEmail(AbstractPhaseHandler.java:652)
        ... 14 more
Caused by: java.lang.IllegalArgumentException: ratingType should not be null.
        at com.cronos.onlinereview.external.UserProjectDataStoreHelper.validateNull(UserProjectDataStoreHelper.java:54)
        at com.cronos.onlinereview.external.RatingInfo.<init>(RatingInfo.java:131)
        at com.cronos.onlinereview.external.impl.DBUserRetrieval.updateRatings(DBUserRetrieval.java:511)

**Comment by RiteshTC** [comment]
cc @dushyantb @ajefts

**Comment by RiteshTC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enabling Ratings for Code Challenges  causing Exception](https://trello.com/c/uFKNmLeM/45-enabling-ratings-for-code-challenges-causing-exception)

**Comment by coderReview** [comment]
solution provided in slack and committed code.
